version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: cicd/Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cicd/reportes:/var/jenkins_home/workspace/reportes
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true
    depends_on:
      - sonarqube

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  jenkins_home:
  pgdata:
